services:
  acurite-interceptor:
    image: acurite
    container_name: acurite-interceptor
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      INFLUXDB_HOST: http://IP:PORT
      MQTT_URL: mqtt://IP:PORT
      HOST: "FQDN or IP"
      ACURITE_IPS: "IPs CSV"
